channels:
- defaults
- conda-forge
- pytorch
dependencies:
- python=3.8.2
- pip
- pip:
  - matplotlib
  - torch>=1.9.0
  - pytorch-lightning>=1.7.6
  - mlflow>=1.14.0
  - captum
  - webdataset
  - sklearn
  - torchvision
